config/routes.rb
Rails.application.routes.draw do
  resources :simplo_orders
  resources :order_stores
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: redirect('orders/index')
  get 'orders/index', to: 'orders#index', as: 'index'
  get 'orders/immediate_delivery', to: 'orders#immediate_delivery', as: 'immediate_delivery'
  get 'orders/motoboy', to: 'orders#motoboy', as: 'motoboy'
  get 'orders/index/:order_status', to: 'orders#filter_index', as: 'filter_index'
  get 'orders/discount_message', to: 'orders#discount_message', as: 'discount_message'
  get 'orders/discount_message/:order_status', to: 'orders#filter_discount_message', as: 'filter_discount_message'
  get 'orders/exchanges', to: 'orders#exchanges', as: 'exchanges'
  post 'orders/update_order_status', to: 'orders#update_order_status', as: 'update_order_status'
end

app/models/simplo_order.rb
# frozen_string_literal: true

class SimploOrder < ApplicationRecord
  def self.integrate_order_items(initial_date)
    initial_date = "?data_inicio=#{initial_date.to_date.strftime('%Y-%m-%d')}" if initial_date.present?
    @order_page = HTTParty.get("https://purchasestore.com.br/ws/wspedidos.json#{initial_date}",
                               headers: { content: 'application/json',
                                          Appkey: 'ZTgyYjMzZDJhMDVjMTVjZWM4OWNiMGU5NjI1NTNkYmU' })
    (1..@order_page['pagination']['page_count']).each do |i|
      @order_page = HTTParty.get("https://purchasestore.com.br/ws/wspedidos.json?page=#{i}",
                                 headers: { content: 'application/json',
                                            Appkey: 'ZTgyYjMzZDJhMDVjMTVjZWM4OWNiMGU5NjI1NTNkYmU' })
      @order_page['result'].each do |order_page|
        order = SimploOrder.find_by(order_id: order_page['Wspedido']['numero'])
        if order.nil?
          SimploOrder.create(name: order_page['Wspedido']['cliente_razaosocial'],
                             order_id: order_page['Wspedido']['numero'],
                             order_status: order_page['Wspedido']['pedidostatus_id'],
                             cliente_cpfcnpj: order_page['Wspedido']['cliente_cpfcnpj'],
                             entrega_logradouro: order_page['Wspedido']['entrega_logradouro'],
                             entrega_numero: order_page['Wspedido']['entrega_numero'],
                             entrega_bairro: order_page['Wspedido']['entrega_bairro'],
                             entrega_cidade: order_page['Wspedido']['entrega_cidade'],
                             entrega_estado: order_page['Wspedido']['entrega_estado'],
                             cliente_informacoes_adicionais: order_page['Wspedido']['cliente_informacoes_adicionais'],
                             envio_servico: order_page['Wspedido']['envio_servico'],
                             nota_fiscal: order_page['Wspedido']['numero'],
                             telephone: order_page['Wspedido']['cliente_telefone'],
                             cep: order_page['Wspedido']['entrega_cep'],
                             email: order_page['Wspedido']['cliente_email'],
                             order_date: Time.parse(order_page['Wspedido']['data_pedido']),
                             total_freight: order_page['Wspedido']['total_frete'],
                             total_products: order_page['Wspedido']['total_produtos'],
                             total_discount: order_page['Wspedido']['total_descontos'],
                             total_value: order_page['Wspedido']['total_pedido'],
                             tracking_object: order_page['Wspedido']['envio_codigo_objeto'])
        elsif order.order_status != order_page['Wspedido']['pedidostatus_id']
          order.update(order_status: order_page['Wspedido']['pedidostatus_id'])
        end
      rescue ArgumentError
        puts 'erro'
      end
    end
  end
end

app/controllers/simplo_orders_controller.rb
class SimploOrdersController < ApplicationController
  before_action :set_simplo_order, only: [:show, :edit, :update, :destroy]

  # GET /simplo_orders
  # GET /simplo_orders.json
  def index
    @simplo_orders = SimploOrder.all
  end

  # GET /simplo_orders/1
  # GET /simplo_orders/1.json
  def show
  end

  # GET /simplo_orders/new
  def new
    @simplo_order = SimploOrder.new
  end

  # GET /simplo_orders/1/edit
  def edit
  end

  # POST /simplo_orders
  # POST /simplo_orders.json
  def create
    @simplo_order = SimploOrder.new(simplo_order_params)

    respond_to do |format|
      if @simplo_order.save
        format.html { redirect_to @simplo_order, notice: 'Simplo order was successfully created.' }
        format.json { render :show, status: :created, location: @simplo_order }
      else
        format.html { render :new }
        format.json { render json: @simplo_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simplo_orders/1
  # PATCH/PUT /simplo_orders/1.json
  def update
    respond_to do |format|
      if @simplo_order.update(simplo_order_params)
        format.html { redirect_to @simplo_order, notice: 'Simplo order was successfully updated.' }
        format.json { render :show, status: :ok, location: @simplo_order }
      else
        format.html { render :edit }
        format.json { render json: @simplo_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simplo_orders/1
  # DELETE /simplo_orders/1.json
  def destroy
    @simplo_order.destroy
    respond_to do |format|
      format.html { redirect_to simplo_orders_url, notice: 'Simplo order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simplo_order
      @simplo_order = SimploOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def simplo_order_params
      params.require(:simplo_order).permit(:order_id, :name, :order_date, :order_status, :telephone, :email)
    end
end

app/helpers/simplo_orders_helper.rb
module SimploOrdersHelper
end

app/views/simplo_orders/_form.html.erb
<%= form_with(model: simplo_order, local: true) do |form| %>
  <% if simplo_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(simplo_order.errors.count, "error") %> prohibited this simplo_order from being saved:</h2>

      <ul>
        <% simplo_order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :order_date %>
    <%= form.datetime_select :order_date %>
  </div>

  <div class="field">
    <%= form.label :order_status %>
    <%= form.text_field :order_status %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/simplo_orders/edit.html.erb
<h1>Editing Simplo Order</h1>

<%= render 'form', simplo_order: @simplo_order %>

<%= link_to 'Show', @simplo_order %> |
<%= link_to 'Back', simplo_orders_path %>

app/views/simplo_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Simplo Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Name</th>
      <th>Order date</th>
      <th>Order status</th>
      <th>Telephone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @simplo_orders.each do |simplo_order| %>
      <tr>
        <td><%= simplo_order.order_id %></td>
        <td><%= simplo_order.name %></td>
        <td><%= simplo_order.order_date %></td>
        <td><%= simplo_order.order_status %></td>
        <td><%= simplo_order.telephone %></td>
        <td><%= simplo_order.email %></td>
        <td><%= link_to 'Show', simplo_order %></td>
        <td><%= link_to 'Edit', edit_simplo_order_path(simplo_order) %></td>
        <td><%= link_to 'Destroy', simplo_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Simplo Order', new_simplo_order_path %>

app/views/simplo_orders/new.html.erb
<h1>New Simplo Order</h1>

<%= render 'form', simplo_order: @simplo_order %>

<%= link_to 'Back', simplo_orders_path %>

app/views/simplo_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @simplo_order.order_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @simplo_order.name %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @simplo_order.order_date %>
</p>

<p>
  <strong>Order status:</strong>
  <%= @simplo_order.order_status %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @simplo_order.telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @simplo_order.email %>
</p>

<%= link_to 'Edit', edit_simplo_order_path(@simplo_order) %> |
<%= link_to 'Back', simplo_orders_path %>