config/routes.rb
Rails.application.routes.draw do
  resources :simplo_orders
  resources :order_stores
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: redirect('orders/index')
  get 'orders/index', to: 'orders#index', as: 'index'
  get 'orders/immediate_delivery', to: 'orders#immediate_delivery', as: 'immediate_delivery'
  get 'orders/motoboy', to: 'orders#motoboy', as: 'motoboy'
  get 'orders/index/:order_status', to: 'orders#filter_index', as: 'filter_index'
  get 'orders/discount_message', to: 'orders#discount_message', as: 'discount_message'
  get 'orders/discount_message/:order_status', to: 'orders#filter_discount_message', as: 'filter_discount_message'
  get 'orders/exchanges', to: 'orders#exchanges', as: 'exchanges'
  post 'orders/update_order_status', to: 'orders#update_order_status', as: 'update_order_status'
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController

  def index
    @status_code = {'Seu pedido foi criado com sucesso! Aguardamos o pagamento' => '1', 
                    'Aguardando Pagamento' => '24',
                    'Solicitação de troca ou devolução' => '29',
                    'Pago' => '2',
                    'Sendo fabricado para ser enviado em Porto Alegre' => '31',
                    'Sendo fabricado para ser enviado em São Paulo' => '30',
                    'Agendado para entrega pelo motoboy!' => '33',
                    'Disponível para ser Retirado em Mãos' => '32',
                    'Enviado' => '23',
                    'Entregue' => '3',
                    'Cancelado' => '4'
                  }
  end

  def immediate_delivery
    @status_code = {'Seu pedido foi criado com sucesso! Aguardamos o pagamento' => '1', 
                    'Aguardando Pagamento' => '24',
                    'Solicitação de troca ou devolução' => '29',
                    'Pago' => '2',
                    'Sendo fabricado para ser enviado em Porto Alegre' => '31',
                    'Sendo fabricado para ser enviado em São Paulo' => '30',
                    'Agendado para entrega pelo motoboy!' => '33',
                    'Disponível para ser Retirado em Mãos' => '32',
                    'Enviado' => '23',
                    'Entregue' => '3',
                    'Cancelado' => '4'
                  }
  end

  def motoboy
    @status_code = {'Seu pedido foi criado com sucesso! Aguardamos o pagamento' => '1', 
                    'Aguardando Pagamento' => '24',
                    'Solicitação de troca ou devolução' => '29',
                    'Pago' => '2',
                    'Sendo fabricado para ser enviado em Porto Alegre' => '31',
                    'Sendo fabricado para ser enviado em São Paulo' => '30',
                    'Agendado para entrega pelo motoboy!' => '33',
                    'Disponível para ser Retirado em Mãos' => '32',
                    'Enviado' => '23',
                    'Entregue' => '3',
                    'Cancelado' => '4'
                  }
  end

  def filter_index
    @order_status = params['order_status']
    @status_code = {'Seu pedido foi criado com sucesso! Aguardamos o pagamento' => '1', 
                    'Aguardando Pagamento' => '24',
                    'Solicitação de troca ou devolução' => '29',
                    'Pago' => '2',
                    'Sendo fabricado para ser enviado em Porto Alegre' => '31',
                    'Sendo fabricado para ser enviado em São Paulo' => '30',
                    'Agendado para entrega pelo motoboy!' => '33',
                    'Disponível para ser Retirado em Mãos' => '32',
                    'Enviado' => '23',
                    'Entregue' => '3',
                    'Cancelado' => '4'
                  }
  end

  def discount_message
    @status_code = {'Seu pedido foi criado com sucesso! Aguardamos o pagamento' => '1', 
      'Aguardando Pagamento' => '24',
      'Solicitação de troca ou devolução' => '29',
      'Pago' => '2',
      'Sendo fabricado para ser enviado em Porto Alegre' => '31',
      'Sendo fabricado para ser enviado em São Paulo' => '30',
      'Agendado para entrega pelo motoboy!' => '33',
      'Disponível para ser Retirado em Mãos' => '32',
      'Enviado' => '23',
      'Entregue' => '3',
      'Cancelado' => '4'
    }
    @bank_accounts = "%0aContas bancárias:%0a
                      Itaú %0a
                      Ag: 0187 %0a
                      Conta: 16334-0%0a
                      Larissa rodrigues %0a
                      Conta corrente %0a
                      CPF: 86377329091%0a
                      %0a
                      Banco do Brasill%0a
                      Ag:1899-6%0a
                      Conta corrente:49603-0 %0a
                      CPF:02399708024 %0a
                      Matheus Nunes Puppe %0a
                      %0a
                      Banrisul%0a
                      Agência: 0062 %0a
                      Conta:06.067524.0-2 %0a
                      Purchase Store %0a
                      CNPJ: 33629.474/000156 %0a
                      Conta Corrente %0a
                      %0a
                      Caixa federal  %0a
                      Ag 3775 %0a
                      Op 013 %0a
                      Conta 6446-1 %0a
                      Matheus Nunes Puppe  %0a
                      CPF: 02399708024 %0a
                      %0a
                      Santander %0a
                      Ag: 2124 %0a
                      CC: 130013193 %0a
                      Matheus Nunes Puppe %0a
                      Purchase Store%0a"
  end

  def filter_discount_message
    @order_status = params['order_status']
    @status_code = {'Seu pedido foi criado com sucesso! Aguardamos o pagamento' => '1', 
      'Aguardando Pagamento' => '24',
      'Solicitação de troca ou devolução' => '29',
      'Pago' => '2',
      'Sendo fabricado para ser enviado em Porto Alegre' => '31',
      'Sendo fabricado para ser enviado em São Paulo' => '30',
      'Agendado para entrega pelo motoboy!' => '33',
      'Disponível para ser Retirado em Mãos' => '32',
      'Enviado' => '23',
      'Entregue' => '3',
      'Cancelado' => '4'
    }
    @bank_accounts = "%0aContas bancárias:%0a
                      Itaú %0a
                      Ag: 0187 %0a
                      Conta: 16334-0%0a
                      Larissa rodrigues %0a
                      Conta corrente %0a
                      CPF: 86377329091%0a
                      %0a
                      Banco do Brasill%0a
                      Ag:1899-6%0a
                      Conta corrente:49603-0 %0a
                      CPF:02399708024 %0a
                      Matheus Nunes Puppe %0a
                      %0a
                      Banrisul%0a
                      Agência: 0062 %0a
                      Conta:06.067524.0-2 %0a
                      Purchase Store %0a
                      CNPJ: 33629.474/000156 %0a
                      Conta Corrente %0a
                      %0a
                      Caixa federal  %0a
                      Ag 3775 %0a
                      Op 013 %0a
                      Conta 6446-1 %0a
                      Matheus Nunes Puppe  %0a
                      CPF: 02399708024 %0a
                      %0a
                      Santander %0a
                      Ag: 2124 %0a
                      CC: 130013193 %0a
                      Matheus Nunes Puppe %0a
                      Purchase Store%0a"
  end

  def update_order_status
    SimploOrder.integrate_order_items(params['query'])
    redirect_to root_path
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/discount_message.html.erb
<table id="order_table" class="table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Id Pedido</th>
      <th>Name</th>
      <th>Data Pedido</th>
      <th>Status pedido</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>CEP</th>
      <th>Rastreamento</th>
      <th>Mensagem WhatsApp PC</th>
      <th>Mensagem WhatsApp Celular</th>
    </tr>
  </thead>
  <tbody>
    <% SimploOrder.all.each do |order| %>
      <tr>
        <td><%= order.order_id %></td>
        <td><%= order.name %></td>
        <td><%= order.order_date.strftime("%-d/%-m/%Y %H:%M") %></td>
        <td><%= @status_code.key(order.order_status)%></td>
        <td><%= order.telephone %></td>
        <td><%= order.email %></td>
        <td><%= order.cep %></td>
        <td><%= order.tracking_object %></td>
        <td><a href="https://web.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, seu pedido <%= order.order_id %> está para ser cancelado, mas eu consegui um desconto de <%= order.total_value %> para <%= ((order.total_value).to_f * 0.87).round(2) %> se você efetuar o pagamento até as 18h de hoje(<%= Date.today.strftime("%-d/%-m/%Y") %>). Segue as contas para depósito: <%= @bank_accounts %> Qualquer dúvida fico a disposição!" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>        
        <td><a href="https://api.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, seu pedido <%= order.order_id %> está para ser cancelado, mas eu consegui um desconto de <%= order.total_value %> para <%= ((order.total_value).to_f * 0.87).round(2) %> se você efetuar o pagamento até as 18h de hoje(<%= Date.today.strftime("%-d/%-m/%Y") %>). Segue as contas para depósito: <%= @bank_accounts %> Qualquer dúvida fico a disposição!" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/filter_discount_message.html.erb
<table id="order_table" class="table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Id Pedido</th>
      <th>Name</th>
      <th>Data Pedido</th>
      <th>Status pedido</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>CEP</th>
      <th>Rastreamento</th>
      <th>Mensagem WhatsApp PC</th>
      <th>Mensagem WhatsApp Celular</th>
    </tr>
  </thead>
  <tbody>
    <% SimploOrder.where(order_status: @order_status).each do |order| %>
      <tr>
        <td><%= order.order_id %></td>
        <td><%= order.name %></td>
        <td><%= order.order_date.strftime("%-d/%-m/%Y %H:%M") %></td>
        <td><%= @status_code.key(order.order_status)%></td>
        <td><%= order.telephone %></td>
        <td><%= order.email %></td>
        <td><%= order.cep %></td>
        <td><%= order.tracking_object %></td>
        <td><a href="https://web.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, seu pedido <%= order.order_id %> está para ser cancelado, mas eu consegui um desconto de <%= order.total_value %> para <%= ((order.total_value).to_f * 0.87).round(2) %> se você efetuar o pagamento até as 18h de hoje(<%= Date.today.strftime("%-d/%-m/%Y") %>). Segue as contas para depósito: <%= @bank_accounts %> Qualquer dúvida fico a disposição!" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>        
        <td><a href="https://api.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, seu pedido <%= order.order_id %> está para ser cancelado, mas eu consegui um desconto de <%= order.total_value %> para <%= ((order.total_value).to_f * 0.87).round(2) %> se você efetuar o pagamento até as 18h de hoje(<%= Date.today.strftime("%-d/%-m/%Y") %>). Segue as contas para depósito: <%= @bank_accounts %> Qualquer dúvida fico a disposição!" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/filter_index.html.erb
<table id="order_table" class="table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Id Pedido</th>
      <th>Name</th>
      <th>Data Pedido</th>
      <th>Status pedido</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>CEP</th>
      <th>Rastreamento</th>
      <th>Mensagem WhatsApp PC</th>
      <th>Mensagem WhatsApp Celular</th>
    </tr>
  </thead>
  <tbody>
    <% SimploOrder.where(order_status: @order_status).each do |order| %>
      <tr>
        <td><%= order.order_id %></td>
        <td><%= order.name %></td>
        <td><%= order.order_date.strftime("%-d/%-m/%Y %H:%M") %></td>
        <td><%= @status_code.key(order.order_status)%></td>
        <td><%= order.telephone %></td>
        <td><%= order.email %></td>
        <td><%= order.cep %></td>
        <td><%= order.tracking_object %></td>
        <td><a href="https://web.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, sou a Lari da Purchase e recebemos o teu pedido <%= order.order_id %> no site. Vi que seu pagamento é em depósito ou cartão, assim que efetuar pode mandar o comprovante pra mim! Em 3 dias após criado o pedido é cancelado automaticamente. Estou a disposição para tirar suas dúvidas ou informações! ❤" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>        
        <td><a href="https://api.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, sou a Lari da Purchase e recebemos o teu pedido <%= order.order_id %> no site. Vi que seu pagamento é em depósito ou cartão, assim que efetuar pode mandar o comprovante pra mim! Em 3 dias após criado o pedido é cancelado automaticamente. Estou a disposição para tirar suas dúvidas ou informações! ❤" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/immediate_delivery.html.erb
<h3><%= link_to "PEDIDO criado", index_path %></h3>
<h3><%= link_to "Pedido Motoboy", motoboy_path %></h3>
<table id="order_table" class="table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Id Pedido</th>
      <th>Name</th>
      <th>Data Pedido</th>
      <th>Status pedido</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>CEP</th>
      <th>Rastreamento</th>
      <th>Mensagem WhatsApp PC</th>
      <th>Mensagem WhatsApp Celular</th>
    </tr>
  </thead>
  <tbody>
    <% SimploOrder.all.each do |order| %>
      <tr>
        <td><%= order.order_id %></td>
        <td><%= order.name %></td>
        <td><%= order.order_date.strftime("%-d/%-m/%Y %H:%M") %></td>
        <td><%= @status_code.key(order.order_status)%></td>
        <td><%= order.telephone %></td>
        <td><%= order.email %></td>
        <td><%= order.cep %></td>
        <td><%= order.tracking_object %></td>
        <td><a href="https://web.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, sou a Lari da Purchase 🥰! Estou passando para avisar que chegou reposição do seu pedido <%= order.order_id %>. Efetuando o pagamento ainda hoje, consigo fazer o envio em até 24h.Ficou com alguma dúvida? Fico á disposição. ❤️✨" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>        
        <td><a href="https://api.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, sou a Lari da Purchase 🥰! Estou passando para avisar que chegou reposição do seu pedido <%= order.order_id %>. Efetuando o pagamento ainda hoje, consigo fazer o envio em até 24h.Ficou com alguma dúvida? Fico á disposição. ❤️✨" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/index.html.erb
<h3><%= link_to "Pedido produto envio imediato", immediate_delivery_path %></h3>
<h3><%= link_to "Pedido Motoboy", motoboy_path %></h3>

<table id="order_table" class="table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Id Pedido</th>
      <th>Name</th>
      <th>Data Pedido</th>
      <th>Status pedido</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>CEP</th>
      <th>Rastreamento</th>
      <th>Mensagem WhatsApp PC</th>
      <th>Mensagem WhatsApp Celular</th>
    </tr>
  </thead>
  <tbody>
    <% SimploOrder.all.each do |order| %>
      <tr>
        <td><%= order.order_id %></td>
        <td><%= order.name %></td>
        <td><%= order.order_date.strftime("%-d/%-m/%Y %H:%M") %></td>
        <td><%= @status_code.key(order.order_status)%></td>
        <td><%= order.telephone %></td>
        <td><%= order.email %></td>
        <td><%= order.cep %></td>
        <td><%= order.tracking_object %></td>
        <td><a href="https://web.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, sou a Lari da Purchase e recebemos o teu pedido <%= order.order_id %> no site. Vi que seu pagamento é em depósito ou cartão, assim que efetuar pode mandar o comprovante pra mim! Em 3 dias após criado o pedido é cancelado automaticamente. Estou a disposição para tirar suas dúvidas ou informações! ❤" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>        
        <td><a href="https://api.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, sou a Lari da Purchase e recebemos o teu pedido <%= order.order_id %> no site. Vi que seu pagamento é em depósito ou cartão, assim que efetuar pode mandar o comprovante pra mim! Em 3 dias após criado o pedido é cancelado automaticamente. Estou a disposição para tirar suas dúvidas ou informações! ❤" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/motoboy.html.erb
<h3><%= link_to "PEDIDO criado", index_path %></h3>
<h3><%= link_to "Pedido produto envio imediato", immediate_delivery_path %></h3>
<table id="order_table" class="table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Id Pedido</th>
      <th>Name</th>
      <th>Data Pedido</th>
      <th>Status pedido</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>CEP</th>
      <th>Rastreamento</th>
      <th>Mensagem WhatsApp PC</th>
      <th>Mensagem WhatsApp Celular</th>
    </tr>
  </thead>
  <tbody>
    <% SimploOrder.all.each do |order| %>
      <tr>
        <td><%= order.order_id %></td>
        <td><%= order.name %></td>
        <td><%= order.order_date.strftime("%-d/%-m/%Y %H:%M") %></td>
        <td><%= @status_code.key(order.order_status)%></td>
        <td><%= order.telephone %></td>
        <td><%= order.email %></td>
        <td><%= order.cep %></td>
        <td><%= order.tracking_object %></td>
        <td><a href="https://web.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, sou a Lari da Purchase 🥰! Estou com seu pedido em mãos, e vi que o envio solicitado é via motoboy! Deseja receber ainda hoje? 😃 Lembrando que, o pagamento pode ser feito via pix, ou, no momento da entrega do produto (Dinheiro ou cartões débito/crédito). Ficou com alguma dúvida? Fico á disposição. ❤️✨" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>        
        <td><a href="https://api.whatsapp.com/send?phone=55<%= order.telephone.delete'() ' %>&amp;text=Oi <%= order.name.split(" ").first %>, sou a Lari da Purchase 🥰! Estou com seu pedido em mãos, e vi que o envio solicitado é via motoboy! Deseja receber ainda hoje? 😃 Lembrando que, o pagamento pode ser feito via pix, ou, no momento da entrega do produto (Dinheiro ou cartões débito/crédito). Ficou com alguma dúvida? Fico á disposição. ❤️✨" target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>        
      </tr>
    <% end %>
  </tbody>
</table>