config/routes.rb
Rails.application.routes.draw do
  resources :simplo_orders
  resources :order_stores
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: redirect('orders/index')
  get 'orders/index', to: 'orders#index', as: 'index'
  get 'orders/immediate_delivery', to: 'orders#immediate_delivery', as: 'immediate_delivery'
  get 'orders/motoboy', to: 'orders#motoboy', as: 'motoboy'
  get 'orders/index/:order_status', to: 'orders#filter_index', as: 'filter_index'
  get 'orders/discount_message', to: 'orders#discount_message', as: 'discount_message'
  get 'orders/discount_message/:order_status', to: 'orders#filter_discount_message', as: 'filter_discount_message'
  get 'orders/exchanges', to: 'orders#exchanges', as: 'exchanges'
  post 'orders/update_order_status', to: 'orders#update_order_status', as: 'update_order_status'
end

app/models/order_store.rb
class OrderStore < ApplicationRecord

	def self.list_orders
		for i in 1..20
  		@orders = HTTParty.get("https://purchasestore.com.br/ws/wspedidos.json?page=#{i}?data_inicio=2021-04-01",
               headers: { content: 'application/json',
                          Appkey: 'ZTgyYjMzZDJhMDVjMTVjZWM4OWNiMGU5NjI1NTNkYmU' })
			@orders["result"].each do |order|
				if order["Wspedido"]["pedidostatus_id"] != '24' && order["Wspedido"]["pedidostatus_id"] != '1' && order["Wspedido"]["pedidostatus_id"] != '4' #vendas diárias
				# if order["Wspedido"]["pedidostatus_id"] == '23' || order["Wspedido"]["pedidostatus_id"] == '30'
					# if order["Wspedido"]['pagamento_forma'] != 'Depósito Bancário' #pagarme
						OrderStore.create(status: order["Wspedido"]["pedidostatus_id"], value: order["Wspedido"]["total_pedido"], order_date: order["Wspedido"]["data_pedido"])
					# end
				end
			end
		end
	end
end

app/controllers/order_stores_controller.rb
class OrderStoresController < ApplicationController
  before_action :set_order_store, only: [:show, :edit, :update, :destroy]

  # GET /order_stores
  # GET /order_stores.json
  def index
    @order_stores = OrderStore.all.order(order_date: :desc)
  end

  # GET /order_stores/1
  # GET /order_stores/1.json
  def show
  end

  # GET /order_stores/new
  def new
    @order_store = OrderStore.new
  end

  # GET /order_stores/1/edit
  def edit
  end

  # POST /order_stores
  # POST /order_stores.json
  def create
    @order_store = OrderStore.new(order_store_params)

    respond_to do |format|
      if @order_store.save
        format.html { redirect_to @order_store, notice: 'Order store was successfully created.' }
        format.json { render :show, status: :created, location: @order_store }
      else
        format.html { render :new }
        format.json { render json: @order_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_stores/1
  # PATCH/PUT /order_stores/1.json
  def update
    respond_to do |format|
      if @order_store.update(order_store_params)
        format.html { redirect_to @order_store, notice: 'Order store was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_store }
      else
        format.html { render :edit }
        format.json { render json: @order_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_stores/1
  # DELETE /order_stores/1.json
  def destroy
    @order_store.destroy
    respond_to do |format|
      format.html { redirect_to order_stores_url, notice: 'Order store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_store
      @order_store = OrderStore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_store_params
      params.require(:order_store).permit(:value, :status, :order_date)
    end
end

app/helpers/order_stores_helper.rb
module OrderStoresHelper
end

app/views/order_stores/_form.html.erb
<%= form_with(model: order_store, local: true) do |form| %>
  <% if order_store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_store.errors.count, "error") %> prohibited this order_store from being saved:</h2>

      <ul>
        <% order_store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :order_date %>
    <%= form.datetime_select :order_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_stores/edit.html.erb
<h1>Editing Order Store</h1>

<%= render 'form', order_store: @order_store %>

<%= link_to 'Show', @order_store %> |
<%= link_to 'Back', order_stores_path %>

app/views/order_stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Stores</h1>

<table id="order_table" class="table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Value</th>
      <th>Status</th>
      <th>Order date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_stores.each do |order_store| %>
      <tr>
        <td><%= order_store.value %></td>
        <td><%= order_store.status %></td>
        <td><%= order_store.order_date.strftime("%-d/%-m/%Y %H:%M") %></td>
        <td><%= link_to 'Show', order_store %></td>
        <td><%= link_to 'Edit', edit_order_store_path(order_store) %></td>
        <td><%= link_to 'Destroy', order_store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Store', new_order_store_path %>

app/views/order_stores/new.html.erb
<h1>New Order Store</h1>

<%= render 'form', order_store: @order_store %>

<%= link_to 'Back', order_stores_path %>

app/views/order_stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @order_store.value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order_store.status %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @order_store.order_date %>
</p>

<%= link_to 'Edit', edit_order_store_path(@order_store) %> |
<%= link_to 'Back', order_stores_path %>