config/routes.rb
Rails.application.routes.draw do
  resources :simplo_orders
  resources :order_stores
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: redirect('orders/index')
  get 'orders/index', to: 'orders#index', as: 'index'
  get 'orders/immediate_delivery', to: 'orders#immediate_delivery', as: 'immediate_delivery'
  get 'orders/motoboy', to: 'orders#motoboy', as: 'motoboy'
  get 'orders/index/:order_status', to: 'orders#filter_index', as: 'filter_index'
  get 'orders/discount_message', to: 'orders#discount_message', as: 'discount_message'
  get 'orders/discount_message/:order_status', to: 'orders#filter_discount_message', as: 'filter_discount_message'
  get 'orders/exchanges', to: 'orders#exchanges', as: 'exchanges'
  post 'orders/update_order_status', to: 'orders#update_order_status', as: 'update_order_status'
end

app/views/layouts/_header.html.erb
<%= form_with url: update_order_status_path, method: :post do |form| %>
  <%= form.label :date, "Data Atualização:" %>
  <%= form.text_field :query %>
  <%= form.submit "Atualizar" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaleMessage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css">
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
  <script>
    $(document).ready(function () {
      $('#order_table').DataTable({
        "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
            },
        responsive: true,
          "order": [[ 0, "desc" ]],
          stateSave: true
        } );
      $('.dataTables_length').addClass('bs-select');
    });
  </script>
</html>